### ISSUE TITLE
Quiz Screen

### ISSUE THREAD

**Issue by abayo-luc** [code-gurus/besty#9]
# Tasks

- [ ] Add quiz screen: navigate from home to quiz
- [ ] Add questions
- [ ] Add answers
- [ ] Mark picked answers
- [ ] Add next button
